#!/bin/sh

NODE_NAME=$(curl -s http://localhost:8500/v1/agent/self | jq '.Config.NodeName' | sed -e 's/[^"]*"\([^"]*\)".*/\1/')

CHECK_ID="service:postgresql:check"

STDIN_DATA="$(cat /dev/stdin)"

echo '${NODE_NAME}'

STDIN_DATA=$(echo "${STDIN_DATA}" | jq "map(select(.Node == \"${NODE_NAME}\" and .CheckID == \"${CHECK_ID}\"))")

echo "${STDIN_DATA}" | jq '.'

STATUS=$(echo "${STDIN_DATA}" | jq '.[] | .Status' | sed -e 's/[^"]*"\([^"]*\)".*/\1/')

echo "${STDIN_DATA}" | jq '.'

append_primary_tag() {
    ALREADY_TAG=$(curl -s http://localhost:8500/v1/agent/services | jq '.postgresql | .Tags | map(select(. == "primary")) | length')

    if [ ${ALREADY_TAG} -eq 0 ] ; then
      curl -s http://localhost:8500/v1/agent/services | jq '.postgresql|{id:.ID,name:.Service,tags:(.Tags + ["primary"]),address:.Address,port:.Port}' | curl -s -XPUT http://localhost:8500/v1/agent/service/register -d @-
    fi

    FILE_DATA="$(cat /etc/consul.d/postgresql.json)"
    ALREADY_TAG=$(echo "${FILE_DATA}" | jq '.service | .tags | map(select(. == "primary")) | length')

    if [ ${ALREADY_TAG} -eq 0 ] ; then
      echo "${FILE_DATA}" | jq '.service | {name: .name, tags: (.tags + ["primary"]), address: .address, port: .port, checks: .checks} | {service: .}' > /etc/consul.d/postgresql.json
    fi
}

remove_primary_tag() {
  TAGS=$(curl -s http://localhost:8500/v1/agent/services | jq '.postgresql | .Tags ')

  if [ "$TAGS" != null ] ; then
    curl -s http://localhost:8500/v1/agent/services | jq '.postgresql|{id:.ID,name:.Service,tags:(.Tags - ["primary"]),address:.Address,port:.Port}' | curl -s -XPUT http://localhost:8500/v1/agent/service/register -d @-
  fi

  FILE_DATA="$(cat /etc/consul.d/postgresql.json)"
  TAGS=$(echo "${FILE_DATA}" | jq '.service | .tags ')

  if [ "$TAGS" != null ] ; then
    echo "${FILE_DATA}" | jq '.service | {name: .name, tags: (.tags - ["primary"]), address: .address, port: .port, checks: .checks} | {service: .}' > /etc/consul.d/postgresql.json
  fi
}

self_addr=$(curl -s http://localhost:8500/v1/agent/self | jq -r '.Member.Addr')
pgpool_sv=($(curl -s http://localhost:8500/v1/catalog/service/pgpool-II | jq -r '.[] |.Address'))
stdout=$(sudo -u postgres psql -h ${pgpool_sv[0]} -p 9999 -U application -c 'show pool_nodes;' | grep ${self_addr})
status=$?

if [ $status -ne 0 ]; then
  hostname=$(curl -s http://localhost:8500/v1/agent/self | jq -r '.Member.Name')

  CONSUL_SECRET_KEY=$(cat /etc/consul.d/default.json | jq -r .acl_master_token)
  CONSUL_SECRET_KEY_ENCODED=$(python -c "import urllib; print urllib.quote('${CONSUL_SECRET_KEY}')")
  virtual_addr=$(curl -s http://localhost:8500/v1/kv/cloudconductor/networks/${hostname}/tap1?raw\&token=${CONSUL_SECRET_KEY_ENCODED} | jq -r '.[][][][].virtual_address')

  stdout=$(sudo -u postgres psql -h ${pgpool_sv[0]} -p 9999 -U application -c 'show pool_nodes;' | grep ${virtual_addr})
  status=$?
fi

values=($(echo ${stdout} | tr -d '|'))
db_role=$(echo ${values[5]})

if [[ "${STATUS}" = "passing" ]] && [ $status -ne 0 -o "${db_role}" = "primary" ] ; then
  ALREADY_EXISTS=$(curl http://localhost:8500/v1/catalog/services | jq '.postgresql | contains(["primary"])')

  if [ "${ALREADY_EXISTS}" != "true" ]; then
    stdout=$(ls /var/lib/pgsql/**/data/recovery.done)
    status=$?

    if [ ${status} -eq 0 ] ; then
      append_primary_tag
    fi
  fi
else
  remove_primary_tag
fi
