default['pgpool_part']['postgresql']['version'] = '9.4'
default['pgpool_part']['postgresql']['dir'] = "/var/lib/pgsql/#{node['pgpool_part']['postgresql']['version']}/data"
default['pgpool_part']['postgresql']['port'] = 5432
default['pgpool_part']['postgresql']['application']['user'] = 'application'
default['pgpool_part']['postgresql']['replication']['check_user'] = 'repcheck'
default['pgpool_part']['postgresql']['tomcat']['user'] = 'tomcat'

default['pgpool_part']['repository']['baseurl'] = 'http://www.pgpool.net/yum/rpms/3.4/redhat/rhel-6-x86_64/'
default['pgpool_part']['repository']['gpgkey'] = 'http://www.pgpool.net/yum/RPM-GPG-KEY-PGPOOL2'
default['pgpool_part']['package_name'] = 'pgpool-II-pg94'
default['pgpool_part']['user'] = 'postgres'
default['pgpool_part']['group'] = 'postgres'
default['pgpool_part']['service'] = 'pgpool'
default['pgpool_part']['config']['dir'] = '/etc/pgpool-II'

default['pgpool_part']['pg_hba']['auth'] = [
  { type: 'host', db: 'all', user: 'all', addr: '127.0.0.1/32', method: 'md5' },
  { type: 'host', db: 'all', user: 'all', addr: '::1/128', method: 'md5' }
]

default[:pgpool_part][:wait_timeout] = 180
default[:pgpool_part][:wait_interval] = 10

default['pgpool_part']['pgconf']['listen_addresses'] = 'localhost'
default['pgpool_part']['pgconf']['port'] = 9999
default['pgpool_part']['pgconf']['socket_dir'] = '/tmp'
default['pgpool_part']['pgconf']['listen_backlog_multiplier'] = 2
default['pgpool_part']['pgconf']['pcp_listen_addresses'] = '*'
default['pgpool_part']['pgconf']['pcp_port'] = 9898
default['pgpool_part']['pgconf']['pcp_socket_dir'] = '/tmp'
default['pgpool_part']['pgconf']['backend_hostname0'] = 'localhost'
default['pgpool_part']['pgconf']['backend_port0'] = 5432
default['pgpool_part']['pgconf']['backend_weight0'] = 1
default['pgpool_part']['pgconf']['backend_data_directory0'] = '/var/lib/pgsql/data'
default['pgpool_part']['pgconf']['backend_flag0'] = 'ALLOW_TO_FAILOVER'
default['pgpool_part']['pgconf']['enable_pool_hba'] = true
default['pgpool_part']['pgconf']['pool_passwd'] = 'pool_passwd'
default['pgpool_part']['pgconf']['authentication_timeout'] = 60
default['pgpool_part']['pgconf']['ssl'] = false
default['pgpool_part']['pgconf']['num_init_children'] = 32
default['pgpool_part']['pgconf']['max_pool'] = 4
default['pgpool_part']['pgconf']['child_life_time'] = 300
default['pgpool_part']['pgconf']['child_max_connections'] = 0
default['pgpool_part']['pgconf']['connection_life_time'] = 0
default['pgpool_part']['pgconf']['client_idle_limit'] = 0
default['pgpool_part']['pgconf']['log_destination'] = 'stderr'
default['pgpool_part']['pgconf']['log_line_prefix'] = '%t: pid %p: '
default['pgpool_part']['pgconf']['log_connections'] = false
default['pgpool_part']['pgconf']['log_hostname'] = false
default['pgpool_part']['pgconf']['log_statement'] = false
default['pgpool_part']['pgconf']['log_per_node_statement'] = false
default['pgpool_part']['pgconf']['log_standby_delay'] = 'none'
default['pgpool_part']['pgconf']['syslog_facility'] = 'LOCAL0'
default['pgpool_part']['pgconf']['syslog_ident'] = 'pgpool'
default['pgpool_part']['pgconf']['debug_level'] = 0
default['pgpool_part']['pgconf']['pid_file_name'] = '/var/run/pgpool/pgpool.pid'
default['pgpool_part']['pgconf']['logdir'] = '/var/log/pgpool'
default['pgpool_part']['pgconf']['connection_cache'] = true
default['pgpool_part']['pgconf']['reset_query_list'] = 'ABORT; DISCARD ALL'
default['pgpool_part']['pgconf']['replication_mode'] = false
default['pgpool_part']['pgconf']['replicate_select'] = false
default['pgpool_part']['pgconf']['insert_lock'] = true
default['pgpool_part']['pgconf']['lobj_lock_table'] = ''
default['pgpool_part']['pgconf']['replication_stop_on_mismatch'] = false
default['pgpool_part']['pgconf']['failover_if_affected_tuples_mismatch'] = false
default['pgpool_part']['pgconf']['load_balance_mode'] = true
default['pgpool_part']['pgconf']['ignore_leading_white_space'] = true
default['pgpool_part']['pgconf']['white_function_list'] = ''
default['pgpool_part']['pgconf']['black_function_list'] = 'nextval,setval,nextval,setval'
default['pgpool_part']['pgconf']['database_redirect_preference_list'] = ''
default['pgpool_part']['pgconf']['app_name_redirect_preference_list'] = ''
default['pgpool_part']['pgconf']['allow_sql_comments'] = false
default['pgpool_part']['pgconf']['master_slave_mode'] = true
default['pgpool_part']['pgconf']['master_slave_sub_mode'] = 'stream'
default['pgpool_part']['pgconf']['sr_check_period'] = 0
default['pgpool_part']['pgconf']['sr_check_user'] = node['pgpool_part']['postgresql']['replication']['check_user']
default['pgpool_part']['pgconf']['sr_check_password'] = ''
default['pgpool_part']['pgconf']['delay_threshold'] = 0
default['pgpool_part']['pgconf']['follow_master_command'] = ''
default['pgpool_part']['pgconf']['health_check_period'] = 0
default['pgpool_part']['pgconf']['health_check_timeout'] = 20
default['pgpool_part']['pgconf']['health_check_user'] = 'nobody'
default['pgpool_part']['pgconf']['health_check_password'] = ''
default['pgpool_part']['pgconf']['health_check_max_retries'] = 0
default['pgpool_part']['pgconf']['health_check_retry_delay'] = 1
default['pgpool_part']['pgconf']['connect_timeout'] = 10000

failover_command = []
failover_command << "NEWPRIMARYNODE=`consul members | grep %H | awk \\'{print $1}\\'`"
failover_command << 'consul event -name="failover" -node="$NEWPRIMARYNODE"'

default['pgpool_part']['pgconf']['failover_command'] = failover_command.join(';')
default['pgpool_part']['pgconf']['failback_command'] = ''
default['pgpool_part']['pgconf']['fail_over_on_backend_error'] = true
default['pgpool_part']['pgconf']['search_primary_node_timeout'] = 10
default['pgpool_part']['pgconf']['recovery_user'] = 'nobody'
default['pgpool_part']['pgconf']['recovery_password'] = ''
default['pgpool_part']['pgconf']['recovery_1st_stage_command'] = ''
default['pgpool_part']['pgconf']['recovery_2nd_stage_command'] = ''
default['pgpool_part']['pgconf']['recovery_timeout'] = 90
default['pgpool_part']['pgconf']['client_idle_limit_in_recovery'] = 0
default['pgpool_part']['pgconf']['use_watchdog'] = true
default['pgpool_part']['pgconf']['trusted_servers'] = ''
default['pgpool_part']['pgconf']['ping_path'] = '/bin'
default['pgpool_part']['pgconf']['wd_hostname'] = node[:ipaddress]
default['pgpool_part']['pgconf']['wd_port'] = 9000
default['pgpool_part']['pgconf']['wd_authkey'] = ''
default['pgpool_part']['pgconf']['delegate_IP'] = ''
default['pgpool_part']['pgconf']['ifconfig_path'] = '/sbin'
default['pgpool_part']['pgconf']['if_up_cmd'] = 'ifconfig eth0:0 inet $_IP_$ netmask 255.255.255.0'
default['pgpool_part']['pgconf']['if_down_cmd'] = 'ifconfig eth0:0 down'
default['pgpool_part']['pgconf']['arping_path'] = '/usr/sbin'
default['pgpool_part']['pgconf']['arping_cmd'] = 'arping -U $_IP_$ -w 1'
default['pgpool_part']['pgconf']['clear_memqcache_on_escalation'] = true
default['pgpool_part']['pgconf']['wd_escalation_command'] = ''
default['pgpool_part']['pgconf']['wd_lifecheck_method'] = 'heartbeat'
default['pgpool_part']['pgconf']['wd_interval'] = 10
default['pgpool_part']['pgconf']['wd_heartbeat_port'] = 9694
default['pgpool_part']['pgconf']['wd_heartbeat_keepalive'] = 2
default['pgpool_part']['pgconf']['wd_heartbeat_deadtime'] = 30
default['pgpool_part']['pgconf']['heartbeat_destination0'] = 'host0_ip1'
default['pgpool_part']['pgconf']['heartbeat_destination_port0'] = 9694
default['pgpool_part']['pgconf']['heartbeat_device0'] = ''
default['pgpool_part']['pgconf']['wd_life_point'] = 3
default['pgpool_part']['pgconf']['wd_lifecheck_query'] = 'SELECT 1'
default['pgpool_part']['pgconf']['wd_lifecheck_dbname'] = 'template1'
default['pgpool_part']['pgconf']['wd_lifecheck_user'] = 'nobody'
default['pgpool_part']['pgconf']['wd_lifecheck_password'] = ''
default['pgpool_part']['pgconf']['relcache_expire'] = 0
default['pgpool_part']['pgconf']['relcache_size'] = 256
default['pgpool_part']['pgconf']['check_temp_table'] = true
default['pgpool_part']['pgconf']['check_unlogged_table'] = true
default['pgpool_part']['pgconf']['memory_cache_enabled'] = false
default['pgpool_part']['pgconf']['memqcache_method'] = 'shmem'
default['pgpool_part']['pgconf']['memqcache_memcached_host'] = 'localhost'
default['pgpool_part']['pgconf']['memqcache_memcached_port'] = 11211
default['pgpool_part']['pgconf']['memqcache_total_size'] = 67108864
default['pgpool_part']['pgconf']['memqcache_max_num_cache'] = 1000000
default['pgpool_part']['pgconf']['memqcache_expire'] = 0
default['pgpool_part']['pgconf']['memqcache_auto_cache_invalidation'] = true
default['pgpool_part']['pgconf']['memqcache_maxcache'] = 409600
default['pgpool_part']['pgconf']['memqcache_cache_block_size'] = 1048576
default['pgpool_part']['pgconf']['memqcache_oiddir'] = '/var/log/pgpool/oiddir'
default['pgpool_part']['pgconf']['white_memqcache_table_list'] = ''
default['pgpool_part']['pgconf']['black_memqcache_table_list'] = ''
